### ISSUE TITLE
Missing CSS for Notebook stdout

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse#27]
This is how stderr looks in Jupyter Notebook:

![_](https://user-images.githubusercontent.com/2401856/67958051-cb216200-fbf6-11e9-9892-b789fb7f24df.png)

This is how it looks like in naucse:

![_](https://user-images.githubusercontent.com/2401856/67958118-e7250380-fbf6-11e9-811c-cd9055cd626d.png)

This happens with any kind of stderr, but for our purposes, it is mostly relevant to warnings. Screenshot from Jupyter Notebook:

![_](https://user-images.githubusercontent.com/2401856/67958288-4256f600-fbf7-11e9-8f9f-30c6693be65e.png)

**Comment by hroncok** [comment]
This makes it look even worse:

```css
div.output_stderr {
  background: #fdd;
  /* very light red background for stderr */
}
```

I would rather not try to fix this myself, my CSS skills are horrible.
